#!/bin/bash

source ./common.sh

function pcurl_wrapper {
    : '
    Curl Proxy Wrapper

    ShortDesc: A wrapper for the curl command that supports optional proxy and SSL certificate usage.

    Description:
    This function provides a convenient way to execute curl commands with optional proxy settings
    and SSL certificate handling. It takes a URL as the first parameter and any additional curl
    parameters as subsequent arguments. If proxy usage is enabled via the USE_PROXY environment variable,
    it configures curl to use the specified proxy. If a base64-encoded SSL certificate is provided,
    it decodes it to a temporary file for use with curl.

    Parameters:
    - url: The URL to be requested with curl.
    - additional_params: Additional parameters to pass to the curl command (optional).

    Environment Variables:
    - USE_PROXY: Set to "true" to enable proxy usage.
    - HTTPS_PROXY: The proxy URL to use if USE_PROXY is true.
    - CERT_BASE64_STRING: Base64-encoded SSL certificate string for verifying proxy connections (optional).

    Returns:
    - 0: Success (curl command executed successfully)
    - 1: Failure (if the curl command fails)

    Example Usage:
    pcurl_wrapper "https://example.com" --verbose --header "User-Agent: CustomAgent"
    '
    local url="$1"
    shift
    local additional_params="$@"

    local curl_cmd="curl"
    local proxy_cmd=""
    local cert_cmd=""

    if [ "${USE_PROXY,,}" == "true" ]; then
        if test_env_variable_defined CERT_BASE64_STRING; then
            # Create a temporary file for the cert
            TEMP_CERT_FILE=$(create_temp_file)
            echo "${CERT_BASE64_STRING}" | base64 -d > "${TEMP_CERT_FILE}"
            cert_cmd="--cacert ${TEMP_CERT_FILE}"
        fi
        proxy_cmd="--proxy ${HTTPS_PROXY}"
    fi

    # Execute curl with the appropriate options
    ${curl_cmd} ${proxy_cmd} ${cert_cmd} ${additional_params} "${url}"

    # Clean up temporary cert file if created
    if [ -n "${TEMP_CERT_FILE}" ]; then
        rm "${TEMP_CERT_FILE}"
    fi
}
